### PR TITLE
Bump antd from 3.26.20 to 4.24.13

### PR DESCRIPTION
**Pull request by bupd**
## Which problem is this PR solving?

- This PR Bumps antd from 3.26.20 to 4.24.13 #1636

## Description of the changes
- Upgraded @types/react to work with antd v4
- Upgrading antd to v4

## How was this change tested?
- By running the required tests

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Comment by yurishkuro** [comment]
What is the purpose of this PR?  We already have the bump attempted by dependabot and already know that it's not passing CI -- https://github.com/jaegertracing/jaeger-ui/pull/1636

**Comment by bupd** [comment]
Hi @yurishkuro,

I've finished upgrading antd icons to v4. I'm now working on modifying the test cases to support the new version.

Once I've finished and confirmed that the tests are passing, I'll push the changes to GitHub and ping you for review.

**Comment by yurishkuro** [comment]
@bupd I strongly advise accumulating very large PR. From what I understand, icons changes can already be applied against antd 3.x, so why not submit small PRs incrementally?

**Comment by mszabo-wikia** [comment]
FYI I have some unfinished prior art over at https://github.com/jaegertracing/jaeger-ui/pull/1261 - feel free to take a look in case you might find something useful.

**Comment by yurishkuro** [comment]
I'll close this in favor of #1636

**Pull request closed without merging**
