### PR TITLE
Docs and a small demo for util/DraggableManager

### PR DESCRIPTION
**Pull request by tiffon**
Per @saminzadeh suggestion, adding docs for `utils/DraggableManager`.

Non-functional change.

Signed-off-by: Joe Farro <joef@uber.com>

### CODE REVIEW

**Comment by yurishkuro** [comment]
personally I'd prefer the README to be in  `src/utils/DraggableManager`, not in ` src/utils/DraggableManager/docs`, because on Github you navigate to `src/utils/DraggableManager` and want to see explanation right there. The example can still be in docs.

**Comment by tiffon** [comment]
@yurishkuro Great point, thanks.

**Comment by yurishkuro** [comment]
why did the test coverage go down? Can the example be excluded from coverage?

**Comment by tiffon** [comment]
>Nice writeup, at some point this might make sense to move to a separate NPM package.

@saminzadeh Hey, that'd be great.

>why did the test coverage go down? Can the example be excluded from coverage?

@yurishkuro Done.

**Pull request merged**
