### PR TITLE
Add a changelog, dates to 2017-08-23

### PR DESCRIPTION
**Pull request by tiffon**
Non-functional change.

Adds a `CHANGELOG.md` document that details merged PRs.

Starts from late August, 2017.

Signed-off-by: Joe Farro <joef@uber.com>

### CODE REVIEW

**Comment by tiffon** [comment]
@yurishkuro Any idea why DCO is not happy with this PR?

**Comment by yurishkuro** [comment]
This info is very useful, but it's not a typical format of the CHANGELOG, which usually has just a few bullet points between releases. In fact, this doc looks more like release notes, maybe we should have a folder for those and record individual files for each release? 

Are all these changes since 0.8.0 backend release?

**Comment by yurishkuro** [comment]
> Any idea why DCO is not happy with this PR?

Did you sign off all commits?  DCO bots checks each commit separately. You can squash them into one and re-upload.

**Comment by tiffon** [comment]
Had to delete remote branch because one of the commits was not signed.

**Pull request closed without merging**
