### PR TITLE
Upgrade antd icons to V4

### PR DESCRIPTION
**Pull request by bupd**
## Which problem is this PR solving?
- Part of #1636 
## Description of the changes
- Changing icons from v3 to v4

## How was this change tested?
- Tested locally everything seems good

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Comment by yurishkuro** [comment]
please include before & after screenshots of the icons.

**Comment by bupd** [comment]
# Before
down_before
Screenshot_2023-08-19_02-07-12

# After
down_after

Screenshot_2023-08-19_02-10-38

**Comment by bupd** [comment]
The antd v4 icons replaces the <i> tags with <span> tags for icons, but the visual appearance and size of the icons remain unchanged. In other words, the change from <i> to <span> does not affect how the icons look on the page.

**Comment by bupd** [comment]
> new ones say Outlined

The Icon type="down" in v3 is exactly the same as <DownOutlined /> in v4 and there are no styling changes. They added outline just to differentiate the base icon from the filled ones.

The main change is instead of importing the whole icon package We import the icons on demand in v4. 

You can refer to these for in depth:

- https://4x.ant.design/docs/react/migration-v4
- https://ant.design/components/icon

**Review by yurishkuro — APPROVED** [review]

**Comment by yurishkuro** [comment]
@bupd any idea why the linter is now failing on the files you changed? Oddly enough, this PR itself was green in CI checks. https://github.com/jaegertracing/jaeger-ui/actions/runs/5919556153/job/16049948626?pr=1636

**Comment by yurishkuro** [comment]
cc @anshgoyalevil

**Comment by bupd** [comment]
> @bupd any idea why the linter is now failing on the files you changed? Oddly enough, this PR itself was green in CI checks. 

Ran the `yarn lint` and other tests locally everything looks good and the tests didn't fail.

- yarn lint no errors found  

tests_passing_antdicons

**Comment by yurishkuro** [comment]
must be caused by the actual upgrade of antd to v4

**Comment by anshgoyalevil** [comment]
Yes, That is caused because of the actual upgrade of `antd` to v4, since it requires a newer version (v18) of react typings, and we are on v16 currently.

**Pull request merged**
