### PR TITLE
Monitor Tab - show 95 Latency in a more readable time-unit

### PR DESCRIPTION
**Pull request by nofar9792**
## Which problem is this PR solving?
Resolves https://github.com/jaegertracing/jaeger-ui/issues/892

## Short description of the changes
before:
Screen Shot 2022-01-25 at 16 09 10

after:
Screen Shot 2022-02-24 at 0 31 09

### CODE REVIEW

**Comment by yurishkuro** [comment]
Don't have a problem with this PR itself, but I am not a fan of this `timeConversion` function, it reduces precision more than necessary. E.g. 5900ms would be displayed as 5s - this is very misleading.

Could we fix this function to:
  1. use rounding, not floor function
  2. keep at least 2 significant digits
  3. use lower-case units

**Comment by nofar9792** [comment]
> Don't have a problem with this PR itself, but I am not a fan of this `timeConversion` function, it reduces precision more than necessary. E.g. 5900ms would be displayed as 5s - this is very misleading.
> 
> Could we fix this function to:
> 
> 1. use rounding, not floor function
> 2. keep at least 2 significant digits
> 3. use lower-case units

lower-case units? change ```timeConversion``` or use in my case ```toLowerCase```>

**Comment by nofar9792** [comment]
> change timeConversion. It's weird that it mixes cases between us/ms and Sec/Hrs



> change timeConversion. It's weird that it mixes cases between us/ms and Sec/Hrs

OK, it is going to affect this place too:
Screen Shot 2022-02-24 at 22 56 07

**Comment by nofar9792** [comment]
> change timeConversion. It's weird that it mixes cases between us/ms and Sec/Hrs

done

**Comment by nofar9792** [comment]
@[yurishkuro](https://github.com/yurishkuro) ping

**Review by yurishkuro — APPROVED** [review]

**Review by yurishkuro — APPROVED** [review]

**Pull request merged**
