### PR TITLE
react-icons upgrade from 2.2.7 to 4.10.1

### PR DESCRIPTION
**Pull request by kirtanchandak**
In this PR I have attempted to upgrade the react-icons version from  2.2.7 to 4.10.1

### CODE REVIEW

**Comment by albertteoh** [comment]
Please sign your commits: https://github.com/jaegertracing/jaeger-ui/pull/1573/checks?check_run_id=14991388577

**Comment by kirtanchandak** [comment]
Hey @albertteoh I signed off the previous commit - 
Screenshot 2023-07-13 164212

**Comment by albertteoh** [comment]
> #### Hey @albertteoh I signed off the previous commit - 
> Screenshot 2023-07-13 164212

You'll need to sign off all commits:

https://github.com/jaegertracing/jaeger-ui/commit/16203e31b2419e7a3fdc2d45d563f377b3fc6e3c

**Comment by albertteoh** [comment]
> Should I open a new PR then?

Yup, that will also work.

**Comment by yurishkuro** [comment]
Simpler is to squash into one commit and sign that.

**Pull request closed without merging**
