### PR TITLE
Bump @types/react from 16.8.7 to 18.2.20

### PR DESCRIPTION
**Pull request by AdityaRaimec22**
## Which problem is this PR solving?
Bump @types/react from 16.8.7 to 18.2.20

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [ ] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Comment by yurishkuro** [comment]
please test locally before submitting PR

**Comment by AdityaRaimec22** [comment]
@yurishkuro I think things will work fine now. Kindly PTAL! Thanks.

**Comment by AdityaRaimec22** [comment]
> please test locally before submitting PR

@yurishkuro I think things will work fine now, kindly PTAL. Thanks!

**Comment by AdityaRaimec22** [comment]
@yurishkuro Kindly PTAL again as I was unable to tun `yarn lint` in my device the unit tests failed here again, but now `yarn lint` is showing no issue with the changhed files so I think things will work fine. Thanks and sorry for inconvenience caused.

**Pull request closed without merging**
