### PR TITLE
Fix linting warnings for all no-unused-vars

### PR DESCRIPTION
**Pull request by DerenToy**
## Which problem is this PR solving?
- Resolves part of no-unused-vars warnings for #1608 

## Description of the changes
-  Unused variables have been removed

## How was this change tested?
- By running "yarn lint" command

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Review by yurishkuro — APPROVED** [review]

**Comment by DerenToy** [comment]
@yurishkuro 
I'm really sorry to bother you again, but I want to ask a question to make sure I don't do anything wrong. You had mentioned it's better for me to open new PRs to fix other eslint errors; is there any downside to creating different branches for each?

**Comment by yurishkuro** [comment]
Thank you!

**Comment by yurishkuro** [comment]
> is there any downside to creating different branches for each?

no, that's precisely what you'd have to do to create different PRs.

**Comment by DerenToy** [comment]
Thank you so much for everything 🙏

**Pull request merged**
