### PR TITLE
Bump redux-actions from v2.2.1 to v2.6.5

### PR DESCRIPTION
**Pull request by anshgoyalevil**
## Which problem is this PR solving?
- This PR upgrades the `redux-actions` package from v2.2.1 to v2.6.5.
- The next version released by the redux-actions team is v3, after 2.6.5, but it doesn't support CJS exports so we can't upgrade to that version.
- relates to: https://github.com/redux-utilities/redux-actions/issues/390
- Also, v3 doesn't include any new feature, so can be ignored: https://github.com/redux-utilities/redux-actions/releases/tag/v3.0.0

## Notable addition:
Since version 2.5.0, package size has been reduced by up to 50%

## How was this change tested?
- locally

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Review by yurishkuro — DISMISSED** [review]

**Comment by anshgoyalevil** [comment]
Strange why ` Cannot find module 'redux-actions' from 'src/reducers/path-agnostic-decorations.tsx'` such errors are there

**Comment by anshgoyalevil** [comment]
Seems like Prathmesh also tried finding a fix for this issue before. https://github.com/redux-utilities/redux-actions/issues/390#issuecomment-1674039758

**Review by yurishkuro — APPROVED** [review]

**Comment by yurishkuro** [comment]
> but it doesn't support CJS exports 

what impact does it have on the UI?

> so we can't upgrade to that version.

then would you suggest we move to some other framework?

**Comment by anshgoyalevil** [comment]
> what impact does it have on the UI?

It (v3.0.0) won't affect anything, neither UI nor any functionality. It's just not working with test files.

> then would you suggest we move to some other framework?

I don't think we should shift to another framework as of now. Since redux is closely packed with the project. Moving to another framework would be like introducing a lot of uncaught bugs.

However since v3.0.0 doesn't support CJS exports, we can wait for the next release. Maybe they would add it back because of opened issues.

**Pull request merged**
