### PR TITLE
[tests] Add tests for formatRelativeDate

### LINKED ISSUE #1747: [tests] Another flaky test seems to be introduced
A couple PRs failed with a drop of code coverage, even though they did not change the code in question (e.g. one was dependencies upgrade). Codecov shows the issue in the date.tsx util file

image

It is possible that the function being tested executes different code paths depending on time of day or some other variable, which should really be controlled better from within the test.

### PR DESCRIPTION
**Pull request by Lauquik**
## Which problem is this PR solving?
- Resolves #1747

## Description of the changes
- added test coverage for formatRelativeDate in /src/utils/date.test.js

## How was this change tested?
-  manually on my local envrionment

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Review by yurishkuro — APPROVED** [review]
thanks!

**Comment by yurishkuro** [comment]
restarted CI, in case it was a spurious error

**Comment by yurishkuro** [comment]
CI succeeded, must have been spurious error - tracked in #1766

**Comment by Lauquik** [comment]
thanks @yurishkuro

**Pull request merged**
