### PR TITLE
Remove unused source-map-explorer package

### PR DESCRIPTION
**Pull request by anshgoyalevil**
## Which problem is this PR solving?
- This PR removes the `source-map-explorer` package because: 
   - It is not being used anywhere inside the project
   - According to its npm desc., it needs to be installed globally, so anyways, not needed inside the project directly. 

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Comment by yurishkuro** [comment]
what are we doing for source maps if we're not using this module?

**Comment by anshgoyalevil** [comment]
I don't think this library is being used anywhere. Where do we have source-maps inside the repository?

**Comment by yurishkuro** [comment]
I don't know, but I am able to see __some__ source code in the Inspector:
image

**Comment by yurishkuro** [comment]
but I can also see the same after applying your PR, so probably fine to merge. It's possible source maps are provided by babel or vite directly.

**Review by yurishkuro — APPROVED** [review]

**Comment by anshgoyalevil** [comment]
Yes. I can see a webpack config for that which uses `source-map`. (It's different from `source-map-explorer`)
```js
output: {
      path: join(__dirname, 'build'),
      publicPath: '/',
      filename: 'assets/[name].js',
    },
```

**Pull request merged**
