### PR TITLE
Use Lerna

### PR DESCRIPTION
**Pull request by tiffon**
The PR reorganizes the repo to use [Lerna](https://lernajs.io/) with the main Jaeger UI app moved into `packages/jaeger-ui`. This is in preparation for developing UI components as independent NPM packages, particularly the directed graph component (#208), so they can be used in other projects as well as Jaeger UI. Lerna eases the development of Jaeger UI as it depends on the separated components.

This also upgrades react to 16.3.2.

### CODE REVIEW

**Comment by tiffon** [comment]
@simonrobb Please look this over when you get the chance.

**Comment by tiffon** [comment]
cc @whistlinwilly

**Comment by saminzadeh** [comment]
Will we need to update the README to develop and run the application?

**Comment by tiffon** [comment]
@saminzadeh Great catch, thanks. I've updated the readme.

**Pull request merged**
