### PR TITLE
Monitor Tab: Cannot choose another timeframe

### PR DESCRIPTION
**Pull request by nofar9792**
## Which problem is this PR solving?
 Resolve (https://github.com/jaegertracing/jaeger-ui/issues/897)

before:

https://user-images.githubusercontent.com/11076023/155885940-fd35d6e5-26a0-489b-8c28-04e3ecf53659.mov

after:

https://user-images.githubusercontent.com/11076023/155885945-e397059e-d938-4ce7-914a-b97b6dc86eba.mov

The issue was the calculation of the timeframe. I did in the constructor and not on every new state

### CODE REVIEW

**Review by albertteoh — DISMISSED** [review]
LGTM, thanks for fixing! Curious, is there a test we could write to prevent this from happening again?

**Comment by nofar9792** [comment]
@albertteoh i added the test + small change in the implementation

**Review by albertteoh — APPROVED** [review]

**Comment by nofar9792** [comment]
@yurishkuro @albertteoh I don't understand why the test coverage decreased.
My changes are not related to ```packages/jaeger-ui/src/components/TracePage/TraceStatistics/tableValues.tsx```

**Comment by albertteoh** [comment]
> I don't understand why the test coverage decreased.

I don't understand the root cause either, but I have observed flakiness in codecov in the past with jaeger-ui PRs. The workaround was to close and re-open the PR to see if it resolves the issue, which I'll try now for you. 

I'd be keen to learn if anyone else has insights on why the codecov check is failing.

**Comment by albertteoh** [comment]
FWIW, a link to what codecov _thinks_ is where the coverage regression exists, which doesn't seem to be related to this PR: https://app.codecov.io/gh/jaegertracing/jaeger-ui/compare/898/changes.

Any ideas @yurishkuro?

**Pull request merged**
