### PR TITLE
Fix linting warnings for no-explicit-any, no-unused-vars, ban-types, ban-ts-comment

### LINKED ISSUE #1608: [chore]: Fix eslint warnings
### What happened?

There some lint warnings shown

### Steps to reproduce

1. Go to the root dir of jaeger-UI
2. run `yarn lint`

### Expected behavior

There should be no eslint warnings

### Relevant log output

```shell
`[eslint       ] 
[eslint       ] /jaeger-ui/packages/jaeger-ui/src/components/SearchTracePage/SearchResults/index.test.js
[eslint       ]   178:23  warning  Unexpected unnamed function  func-names
[eslint       ] 
[eslint       ] /jaeger-ui/packages/jaeger-ui/src/components/SearchTracePage/SearchResults/index.tsx
[eslint       ]   117:18  warning  'createBlob' was used before it was defined  @typescript-eslint/no-use-before-define
[eslint       ] 
[eslint       ] /jaeger-ui/packages/jaeger-ui/src/components/TracePage/TraceStatistics/index.tsx
[eslint       ]   284:13  warning  Avoid non-native interactive elements. If using native HTML is not possible, add an appropriate role and support for tabbing, mouse, keyboard, and touch inputs to an interactive content element  jsx-a11y/no-static-element-interactions
[eslint       ] 
[eslint       ] /jaeger-ui/packages/jaeger-ui/src/selectors/span.js
[eslint       ]   15:1  warning  Prefer default export on a file with single export  import/prefer-default-export
[eslint       ] 
[eslint       ] ✖ 4 problems (0 errors, 4 warnings)
[eslint       ]
```

### Screenshot

image

### Additional context

_No response_

### Jaeger backend version

_No response_

### SDK

_No response_

### Pipeline

_No response_

### Stogage backend

_No response_

### Operating system

_No response_

### Deployment model

_No response_

### Deployment configs

_No response_

### PR DESCRIPTION
**Pull request by DerenToy**
## Which problem is this PR solving?
- Resolves #1608

## Description of the changes
-  I have resolved the ESLint warnings that were generated after running the yarn lint command.

## How was this change tested?
- By running "yarn lint" command

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Comment by yurishkuro** [comment]
Did you just disable all linters for all issues? That's not "fixing" them.

**Comment by DerenToy** [comment]
@yurishkuro
Hello, to be honest, I couldn't fully understand what our approach should be. For example, I understood as if we're expected to suppress the no-explicit-any errors that have been present since 2019-2020. Would it be okay if I fix as many errors as I can without suppressing and open a new PR? Or do I have to fix all errors?

I can fix some ban-types errors and all no-unused-vars errors. For the others, I can try to do research and attempt to fix them without using suppress.

Thank you very much in advance for your answer.

**Comment by yurishkuro** [comment]
Yes, we should always try to fix the errors, not suppress the warnings. There may be some rules that are too painful to fix, so we may ignore them, but that should be done on a case by case basis, not as a blanket solution.

Also, a bit of advice if you're new to open source - **never send PRs that affect 70 files** (unless the changes are done by some automation). Pick a small scope, like a single module, and fix all errors there and submit a PR. Do another module in another PR.  Good read: https://github.com/PlaytikaOSS/small-pull-request-manifesto

**Comment by DerenToy** [comment]
@yurishkuro 
I'm really grateful, thank you so, so, so much. Right now, for example, I've created a PR for all the no-unused-vars errors. https://github.com/jaegertracing/jaeger-ui/pull/1913

For the other numerous errors, as you suggested, I'll break them down into modules and create their PRs. Thank you so, so much 🙏 🙏 🙏

**Pull request closed without merging**
