### PR TITLE
Downgrade react-router-dom (#803)

### LINKED ISSUE #803: Searching spans in a trace page doesn't work
**Describe the bug**
Open a specific trace and enter a span id in the "Find..." textbox does nothing.

**To Reproduce**
1. Open a trace in jaeger ui.
2. Enter a span id in the "Find..." textbox.
3. The url in the browser is updated with the "uiFind=..." parameter but the relevant span isn't marked or found.
4. Refreshing the screen or navigating to the updated url finds the span.
5. No errors were shown in the browser dev tools console, no http errors or calls were made.

**Expected behavior**
When searching a span id the span should be marked and found (nice to have: a message if nothing was found).

**Screenshots**
Entering span id (nothing happens):
Screenshot 2021-08-26 091009

Refreshing the screen with the same url:
Screenshot 2021-08-26 091229

**Version (please complete the following information):**
 - OS: Windows (for the browser), linux for the jaeger backend
 - Jaeger version: all-in-one 1.25.0, jaeger UI version 1.15.0
 - Deployment: local docker (docker desktop) or in kubernetes

**What troubleshooting steps did you try?**
1. Didn't see any errors in the dev tools console.
2. Didn't see any http calls (should be fine I guess since the search is probably done in the client side).
3. Couldn't find any existing issue open in github related to this.

**Additional context**
IIRC the search worked fine a few versions earlier, can't recall which version since I upgraded the docker image several times in the past month.
As a workaround refreshing the screen or navigating directly to the url with the trace and span ids works, just searching in the page seems broken.

### PR DESCRIPTION
**Pull request by w0wka91**
Signed-off-by: Waldemar Penner <waldemar.penner91@gmail.com>

## Which problem is this PR solving?
- Resolves #803

## Short description of the changes
- Downgraded react-router-dom due to incompatibility issues with react-router-redux

### CODE REVIEW

**Comment by w0wka91** [comment]
We could also just revert the PR. The original PR just changed some formatting and made 2 simple changes to tests. So either way should be fine

**Comment by yurishkuro** [comment]
@w0wka91 the change to [packages/jaeger-ui/src/index.js](https://github.com/jaegertracing/jaeger-ui/pull/727/files#diff-f22c6b5f17e6ff988bc0e38832c0c3815f743db2b179b9de63cb8c8ba62f50bcL40) looks significant, but not present in your PR. I prefer not to roll back #727 completely if it had useful forward-looking changes.

**Comment by jpkrohling** [comment]
Should this be considered for tomorrow's release?

**Comment by yurishkuro** [comment]
Yes. We need someone w/ React knowledge to look at this

**Comment by jpkrohling** [comment]
@rubenvp8510, could you do a final review?

**Comment by rubenvp8510** [comment]
> @rubenvp8510, could you do a final review?

Sure!  I did a quick review and looks good. I'll do a final review and approve if everything is OK.

**Review by rubenvp8510 — APPROVED** [review]
Looks good!

**Pull request merged**
